---
# tasks file for nginx-install

- name: Allow nginx to modify files in /var/www/
  sefcontext:
    target: '/var/www(/.*)?'
    setype: httpd_sys_content_t
    state: present

- name:  install nginx repo
  yum:
    name:  http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: present

- name: install nginx
  yum:
    name:
      - nginx
    state: present

- name: create folders for sites
  file:
    path: '/var/www/{{ item }}/html'
    state: directory
  with_items:
    - "{{ ansible_nodename }}"

- name: create folders for site config files
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/etc/nginx/site-available'
    - '/etc/nginx/site-enabled'

- name: Archive default nginx file default.conf and remove it
  archive:
    path: /etc/nginx/conf.d/default.conf
    remove: yes

- name: configure firewall for hosts in group "proxy"
  firewalld:
    port: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - '{{ nginx_fw_ports }}'
  when: inventory_hostname in groups['proxy']

- name: configure firewall rule for hosts in group "web"
  firewalld:
    rich_rule: rule family="ipv4" source address="{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}" service name="http" accept
    permanent: yes
    immediate: yes
    state: enabled
  with_inventory_hostnames:
    - proxy
  when: inventory_hostname in groups['web']
