---

- hosts: all
  become: yes
  roles:
    - { role: common, tags: common }

- hosts: proxy
  become: yes
  roles:
    - { role: certbot, tags: certbot }


- hosts: proxy,web
  become: yes
  roles:
    - { role: nginx, tags: nginx }
